### ISSUE TITLE
Is this free for commercial use?

### ISSUE THREAD

**Issue by mxdubois** [nmcclatchey/Priority-Deque#1]
I see it's a boost candidate, but I thought I should check since there's no license included. 

And would you say it's production ready?

Thanks!

**Comment by mxdubois** [comment]
Oh! I just saw the license in the code :)

I'd still be interested in your opinion about it's current state of stability though, if you get a chance to reply.

**Comment by nmcclatchey** [comment]
I would say it's production-ready; there have been no bugs discovered for a
while now. There is a future update planned (for when I have time), but
it's intended purpose is to add a Boost.Heap-style priority deque, in
addition to the current STL-style priority deque, so it is safe to use the
STL-style deque.
