### ISSUE TITLE
Self move assign issue.

### ISSUE THREAD

**Issue by landwehrj** [nmcclatchey/Priority-Deque#2]
On [interval_heap.hpp:273](https://github.com/nmcclatchey/Priority-Deque/blob/ed5d9cfeccefb2e65dcf3b75ee714d2a1cc109a7/interval_heap.hpp#L273)

The  swap(*first, *last); can do a self swap which fails in older gcc's before 11.2 when using debug mode because it was undefined behavior. It would say something like "Error: attempt to self move assign."

Simply add if (first != last) before the swap to fix it.

This issue is because of the following behavior:
https://github.com/gcc-mirror/gcc/commit/c2fb0a1a2e7a0fb15cf3cf876f621902ccd273f0#

**Comment by nmcclatchey** [comment]
Should be resolved as of 5611cbf6c1d2e0ccce6492f33ad2ab76e30e849d.
